services:
  node-app:
    build: .
    container_name: node-app
    restart: always
    environment:
      DB_USER: user
      DB_PASS: password
      DB_NAME: employeedb
      MASTER_HOST: mysql-master
      MASTER_PORT: 3306
      REPLICA_HOST: mysql-replica
      REPLICA_PORT: 3307
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "9000:9000"
    depends_on:
      - mysql-master
      - mysql-replica
      - redis
    networks:
      - app-network

  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employeedb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-master-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --server-id=1 --log-bin=mysql-bin
    networks:
      - app-network

  mysql-replica:
    image: mysql:8.0
    container_name: mysql-replica
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employeedb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    depends_on:
      - mysql-master
    volumes:
      - mysql-replica-data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password --server-id=2 --relay-log=mysql-relay-bin --log-slave-updates=1 --read-only=1

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6378:6379"
    networks:
      - app-network

volumes:
  mysql-master-data:
  mysql-replica-data:

networks:
  app-network:
    driver: bridge
