version: '3'
services:
  app:
    build: .
    ports:
      - "6000:6000"
    depends_on:
      - redis
      - mysql
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=employeedb

  redis:
    image: redis
    ports:
      - "6378:6379"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employeedb
    ports:
      - "3306:3306"
